<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Thexpand\Zf2HttpCache\Module'                       => __DIR__ . '/src/Zf2HttpCache/Module.php',
    'Thexpand\Zf2HttpCache\View\Helper\Esi'              => __DIR__ . '/src/Zf2HttpCache/View/Helper/Esi.php',
    'Thexpand\Zf2HttpCache\Service\EsiViewHelperFactory' => __DIR__ . '/src/Zf2HttpCache/Service/EsiViewHelperFactory.php',
);
